import { useAuth } from "@/_core/hooks/useAuth";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle } from "@/components/ui/alert-dialog";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { isAdministrator } from "@/lib/roleAccess";
import { CheckCircle2, Clock3, ShieldAlert, Users } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

const roles = ["citizen", "bank", "authority", "admin"] as const;
const roleColor = { citizen: "bg-[#dff4ef] text-[#1d6971]", bank: "bg-[#e6edfb] text-[#385b98]", authority: "bg-[#f4eadc] text-[#86622e]", admin: "bg-[#f0e6f7] text-[#6d3f8f]" } as const;
type Role = (typeof roles)[number];
type PendingChange = { userId: number; name: string; previousRole: Role; nextRole: Role };

const readableRole = (role: Role) => role.charAt(0).toUpperCase() + role.slice(1);
const dateTime = (value: Date | string | null) => value ? new Date(value).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" }) : "—";

export default function AdminUsers() {
  const { user } = useAuth();
  const isAdmin = isAdministrator(user?.role);
  const utils = trpc.useUtils();
  const { data: users = [], isLoading: usersLoading } = trpc.users.list.useQuery(undefined, { enabled: isAdmin });
  const { data: history = [], isLoading: historyLoading } = trpc.users.roleHistory.useQuery(undefined, { enabled: isAdmin });
  const [pendingChange, setPendingChange] = useState<PendingChange | null>(null);
  const changeRole = trpc.users.changeRole.useMutation({
    onSuccess: result => { utils.users.list.invalidate(); utils.users.roleHistory.invalidate(); setPendingChange(null); toast.success(result.changed ? "Role updated and the user has been notified." : "This user already has that role."); },
    onError: error => toast.error(error.message),
  });

  if (!isAdmin) return <div className="mx-auto max-w-2xl rounded-[2rem] border border-[#ebd7ce] bg-[#fff9f7] p-8 text-center"><ShieldAlert className="mx-auto h-8 w-8 text-[#bd654a]" /><h1 className="font-display mt-4 text-3xl text-[#4d2d28]">Administrator access required.</h1><p className="mt-3 text-sm leading-6 text-[#7c5b54]">This area is protected for LienGuard administrators. Your current access has not been changed.</p></div>;

  return <div className="mx-auto max-w-6xl space-y-7">
    <section className="flex flex-col justify-between gap-5 rounded-[2rem] border border-[#dfe3e7] bg-white p-6 shadow-sm sm:flex-row sm:items-end sm:p-8"><div><p className="font-mono text-[0.65rem] uppercase tracking-[0.18em] text-[#6b7c92]">Administrator workflow</p><h1 className="font-display mt-2 text-4xl text-[#20314c]">User access, made legible.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#66758a]">Review authenticated users, assign the right workspace role, and maintain a transparent access record.</p></div><div className="flex items-center gap-3 rounded-2xl bg-[#f0f8f6] px-4 py-3"><div className="grid h-9 w-9 place-items-center rounded-xl bg-white text-[#1f7478] shadow-sm"><Users className="h-4 w-4" /></div><div><p className="text-sm font-semibold text-[#254e55]">Role assignments</p><p className="text-xs text-[#598083]">Create a notice automatically</p></div></div></section>
    <section className="grid gap-5 lg:grid-cols-[1.5fr_0.8fr]"><Card className="border-[#dfe3e7] shadow-sm"><CardContent className="p-0"><div className="flex items-center justify-between border-b border-[#e4e9e9] px-6 py-5"><div><h2 className="font-display text-2xl text-[#20314c]">Authenticated users</h2><p className="mt-1 text-xs text-[#718095]">Users appear after their first secure sign-in.</p></div><Badge variant="secondary" className="bg-[#f0f2f2] text-[#52627a]">{users.length} total</Badge></div>{usersLoading ? <div className="space-y-3 p-6">{[1, 2, 3].map(item => <Skeleton key={item} className="h-16 w-full" />)}</div> : users.length === 0 ? <div className="p-10 text-center"><Users className="mx-auto h-7 w-7 text-[#8aa1aa]" /><p className="mt-4 font-medium text-[#334966]">No users yet.</p><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-[#718095]">People appear here as soon as they complete their first Manus OAuth sign-in.</p></div> : <div className="overflow-x-auto"><table className="w-full min-w-[740px] text-left"><thead className="bg-[#fafbfb] font-mono text-[0.6rem] uppercase tracking-[0.14em] text-[#718095]"><tr><th className="px-6 py-3 font-medium">User</th><th className="px-4 py-3 font-medium">Current role</th><th className="px-4 py-3 font-medium">Last signed in</th><th className="px-6 py-3 text-right font-medium">Assign role</th></tr></thead><tbody>{users.map(record => <tr key={record.id} className="border-t border-[#edf0f0]"><td className="px-6 py-4"><p className="text-sm font-medium text-[#273c59]">{record.name || "Unnamed user"}</p><p className="mt-1 text-xs text-[#738094]">{record.email || "No email provided"}</p></td><td className="px-4 py-4"><Badge className={`${roleColor[record.role]} border-0`}>{readableRole(record.role)}</Badge></td><td className="px-4 py-4 text-xs text-[#718095]">{dateTime(record.lastSignedIn)}</td><td className="px-6 py-4 text-right"><Select value={record.role} disabled={record.id === user.id || changeRole.isPending} onValueChange={value => setPendingChange({ userId: record.id, name: record.name || "this user", previousRole: record.role, nextRole: value as Role })}><SelectTrigger className="ml-auto w-36 rounded-xl bg-white"><SelectValue /></SelectTrigger><SelectContent>{roles.map(role => <SelectItem key={role} value={role}>{readableRole(role)}</SelectItem>)}</SelectContent></Select></td></tr>)}</tbody></table></div>}</CardContent></Card>
      <Card className="border-[#dfe3e7] bg-[#20314c] text-white shadow-sm"><CardContent className="p-6"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#9fe2d3] text-[#20314c]"><ShieldAlert className="h-5 w-5" /></div><p className="mt-6 font-mono text-[0.65rem] uppercase tracking-[0.18em] text-[#9fe2d3]">Controlled change</p><h2 className="font-display mt-2 text-3xl">Keep authority visible.</h2><p className="mt-4 text-sm leading-6 text-slate-300">Every role update creates an audit record and an in-app message for the person whose access changed.</p><div className="mt-7 space-y-3 border-t border-white/10 pt-6"><p className="flex items-center gap-3 text-sm text-slate-200"><CheckCircle2 className="h-4 w-4 text-[#9fe2d3]" />Server-side authorization</p><p className="flex items-center gap-3 text-sm text-slate-200"><CheckCircle2 className="h-4 w-4 text-[#9fe2d3]" />Self-role changes prevented</p><p className="flex items-center gap-3 text-sm text-slate-200"><CheckCircle2 className="h-4 w-4 text-[#9fe2d3]" />Affected user notified</p></div></CardContent></Card>
    </section>
    <Card className="border-[#dfe3e7] shadow-sm"><CardContent className="p-0"><div className="border-b border-[#e4e9e9] px-6 py-5"><div className="flex items-center gap-3"><Clock3 className="h-4 w-4 text-[#4d878b]" /><div><h2 className="font-display text-2xl text-[#20314c]">Recent access history</h2><p className="mt-1 text-xs text-[#718095]">The last 100 role assignments recorded by LienGuard.</p></div></div></div>{historyLoading ? <div className="space-y-3 p-6">{[1, 2].map(item => <Skeleton key={item} className="h-14 w-full" />)}</div> : history.length === 0 ? <p className="p-8 text-sm text-[#718095]">No role changes have been recorded yet.</p> : <div className="divide-y divide-[#edf0f0]">{history.map(entry => <div key={entry.id} className="flex flex-wrap items-center justify-between gap-3 px-6 py-4"><p className="text-sm text-[#31465f]">User ID <span className="font-mono text-xs">#{entry.targetUserId}</span> changed from <Badge className={`${roleColor[entry.previousRole]} mx-1 border-0`}>{readableRole(entry.previousRole)}</Badge> to <Badge className={`${roleColor[entry.newRole]} mx-1 border-0`}>{readableRole(entry.newRole)}</Badge></p><p className="text-xs text-[#718095]">{dateTime(entry.createdAt)}</p></div>)}</div>}</CardContent></Card>
    <AlertDialog open={Boolean(pendingChange)} onOpenChange={open => { if (!open && !changeRole.isPending) setPendingChange(null); }}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Confirm role assignment</AlertDialogTitle><AlertDialogDescription>{pendingChange ? `Change ${pendingChange.name} from ${readableRole(pendingChange.previousRole)} to ${readableRole(pendingChange.nextRole)}? LienGuard will record this change and send the user an in-app notification.` : ""}</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={changeRole.isPending}>Cancel</AlertDialogCancel><AlertDialogAction disabled={changeRole.isPending} onClick={event => { event.preventDefault(); if (pendingChange) changeRole.mutate({ userId: pendingChange.userId, role: pendingChange.nextRole }); }}>{changeRole.isPending ? "Updating…" : "Confirm assignment"}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
  </div>;
}
