import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { FileText, FolderOpen, WandSparkles } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";

export default function Documents() {
  const [, navigate] = useLocation(); const { data: cases = [] } = trpc.cases.list.useQuery(); const [caseId, setCaseId] = useState(""); const selected = cases.find(record => record.caseId === caseId);
  const canDraftRti = Boolean(selected && (selected.status === "ESCALATED" || (selected.status === "AWAITING_RESPONSE" && selected.responseDeadline && new Date(selected.responseDeadline) < new Date())));
  return <div className="mx-auto max-w-5xl space-y-6"><section><p className="eyebrow text-[#688096]">Documents</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight text-[#132f4d]">Build a document from the facts in the record.</h1><p className="mt-2 text-sm text-[#718196]">Select a protected case to review the available record and prepare a fact-based request when the case posture supports it.</p></section><Card className="border-[#dce3eb] shadow-sm"><CardContent className="p-6"><div className="max-w-lg space-y-2"><Label>Case</Label><Select value={caseId} onValueChange={setCaseId}><SelectTrigger><SelectValue placeholder="Select a case" /></SelectTrigger><SelectContent>{cases.map(record => <SelectItem key={record.caseId} value={record.caseId}>{record.caseId} — {record.title}</SelectItem>)}</SelectContent></Select></div>{selected ? <div className="mt-7 grid gap-5 md:grid-cols-2"><section className="rounded-xl border border-[#dce3eb] p-5"><div className="flex items-center gap-3"><FolderOpen className="h-5 w-5 text-[#397295]" /><div><p className="text-sm font-extrabold text-[#2b4963]">Case record</p><p className="text-xs text-[#75879a]">Primary source document</p></div></div><dl className="mt-5 space-y-3 text-sm"><div className="flex justify-between gap-4"><dt className="text-[#718196]">Reference</dt><dd className="font-semibold text-[#34516c]">{selected.caseId}</dd></div><div className="flex justify-between gap-4"><dt className="text-[#718196]">Lien reference</dt><dd className="font-semibold text-[#34516c]">{selected.lienReference || "Not recorded"}</dd></div><div className="flex justify-between gap-4"><dt className="text-[#718196]">Authority</dt><dd className="font-semibold text-[#34516c]">{selected.authorityName || "Not recorded"}</dd></div></dl></section><section className="rounded-xl bg-[#f5f8fb] p-5"><div className="flex items-center gap-3"><FileText className="h-5 w-5 text-[#397295]" /><div><p className="text-sm font-extrabold text-[#2b4963]">RTI draft</p><p className="text-xs text-[#75879a]">Prepared from case posture</p></div></div><p className="mt-5 text-sm leading-6 text-[#66798d]">{canDraftRti ? "This case is eligible for a reviewable RTI draft because of its recorded escalation or deadline state." : "An RTI draft becomes available when this case is escalated or an awaiting-response deadline has passed."}</p><Button disabled={!canDraftRti} onClick={() => navigate("/rti")} className="mt-5 bg-[#0f2b4b] hover:bg-[#183c63]"><WandSparkles className="mr-2 h-4 w-4" />Prepare RTI draft</Button></section></div> : <div className="py-14 text-center"><FileText className="mx-auto h-8 w-8 text-[#7a9fa3]" /><p className="mt-4 text-sm font-semibold text-[#506b83]">{cases.length ? "Select a case to review its documents." : "No case records yet."}</p></div>}</CardContent></Card></div>;
}
