import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { AlertTriangle, ArrowRight, CheckCircle2, Clock3 } from "lucide-react";
import { useLocation } from "wouter";
import { SEO } from "@/components/SEO";

export default function Escalations() {
  const [, navigate] = useLocation(); const { data: cases = [] } = trpc.cases.list.useQuery();
  const now = new Date(); const actionCases = cases.filter(item => item.status === "ESCALATED" || (item.status === "AWAITING_RESPONSE" && item.responseDeadline && new Date(item.responseDeadline) < now));
  return <div className="mx-auto max-w-5xl space-y-6"><SEO title="Escalations — LienGuard" description="Statutory escalation queue" noindex={true} /><section><p className="eyebrow text-[#9a621d]">Escalation status</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight text-[#132f4d]">Resolve the next action with the record in view.</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#718196]">Cases appear here only when their recorded lifecycle is escalated or an awaiting-response deadline has passed.</p></section><div className="grid gap-5 lg:grid-cols-[0.85fr_1.15fr]"><Card className="border-[#dce3eb]"><CardContent className="p-6"><p className="eyebrow text-[#71859a]">Escalation path</p><div className="mt-6 space-y-5">{["Initial authority", "Follow-up record", "Escalation", "RTI assistance"].map((item, index) => <div key={item} className="flex items-center gap-3"><span className={`grid h-7 w-7 place-items-center rounded-full text-xs font-bold ${index < 2 ? "bg-[#e5f4ec] text-[#2b735f]" : "bg-[#eef2f5] text-[#74869a]"}`}>{index < 2 ? "✓" : index + 1}</span><span className="text-sm font-semibold text-[#536c84]">{item}</span></div>)}</div></CardContent></Card><Card className="border-[#dce3eb]"><CardContent className="p-0"><div className="flex items-center gap-3 border-b border-[#e8edf2] p-6"><AlertTriangle className="h-5 w-5 text-[#b45a42]" /><div><p className="eyebrow text-[#71859a]">Action queue</p><h2 className="mt-1 text-lg font-extrabold">Cases requiring review</h2></div></div>{actionCases.length ? <div className="divide-y divide-[#edf0f4]">{actionCases.map(record => <button key={record.caseId} onClick={() => navigate(`/cases/${record.caseId}`)} className="flex w-full items-center justify-between gap-4 px-6 py-5 text-left hover:bg-[#fffaf8]"><div><p className="font-mono text-xs font-bold text-[#a64b3d]">{record.caseId}</p><p className="mt-1 text-sm font-bold text-[#263f59]">{record.title}</p><p className="mt-1 text-xs text-[#75869a]">{record.status === "ESCALATED" ? "Marked escalated" : "Response deadline has passed"}</p></div><ArrowRight className="h-4 w-4 text-[#7a8c9d]" /></button>)}</div> : <div className="p-12 text-center"><CheckCircle2 className="mx-auto h-8 w-8 text-[#3c9374]" /><p className="mt-4 text-sm font-bold text-[#315f57]">No cases need escalation.</p><p className="mt-2 text-sm text-[#718196]">The queue will update from each recorded case status and deadline.</p><Button onClick={() => navigate("/cases")} variant="outline" className="mt-5"><Clock3 className="mr-2 h-4 w-4" />Review case register</Button></div>}</CardContent></Card></div></div>;
}
