import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { Gavel, ListTree } from "lucide-react";
import { useState } from "react";
import { SEO } from "@/components/SEO";

const stamp = (value: Date | string) => new Date(value).toLocaleString(undefined, { dateStyle: "medium", timeStyle: "short" });

export default function Timeline() {
  const { data: cases = [] } = trpc.cases.list.useQuery(); const [caseId, setCaseId] = useState(""); const detail = trpc.cases.detail.useQuery({ caseId }, { enabled: Boolean(caseId) });
  return <div className="mx-auto max-w-5xl space-y-6"><SEO title="Case Timeline — LienGuard" description="Chronological case lifecycle and immutable events" noindex={true} /><section><p className="eyebrow text-[#688096]">Case timeline</p><h1 className="mt-2 text-3xl font-extrabold tracking-tight text-[#132f4d]">Follow the record, step by step.</h1><p className="mt-2 text-sm text-[#718196]">Select a case to inspect its chronological lifecycle. Every entry is generated from data held in the protected record.</p></section><Card className="border-[#dce3eb] shadow-sm"><CardContent className="p-6"><div className="max-w-lg space-y-2"><Label>Case</Label><Select value={caseId} onValueChange={setCaseId}><SelectTrigger><SelectValue placeholder="Select a case timeline" /></SelectTrigger><SelectContent>{cases.map(record => <SelectItem key={record.caseId} value={record.caseId}>{record.caseId} — {record.title}</SelectItem>)}</SelectContent></Select></div>{detail.data ? <div className="mt-8"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#e8f0fa] text-[#2e6794]"><ListTree className="h-4 w-4" /></span><div><p className="text-sm font-extrabold text-[#294660]">{detail.data.case.caseId}</p><p className="text-xs text-[#74869a]">{detail.data.case.title}</p></div></div><ol className="mt-7 space-y-0">{detail.data.timeline.map((event, index) => <li key={event.id} className="relative flex gap-4 pb-8 last:pb-0"><span className={`relative z-10 mt-1 h-3 w-3 rounded-full ${event.tone === "danger" ? "bg-[#c7493a]" : event.tone === "warning" ? "bg-[#d59027]" : event.tone === "success" ? "bg-[#3b9575]" : "bg-[#2e6794]"}`} />{index < detail.data.timeline.length - 1 && <span className="absolute left-[5px] top-5 h-[calc(100%-0.35rem)] w-px bg-[#dce4ec]" />}<div><p className="text-sm font-bold text-[#2d4864]">{event.title}</p><p className="mt-1 text-sm leading-6 text-[#68798c]">{event.detail}</p><time className="mt-1.5 block text-xs text-[#8391a0]">{stamp(event.occurredAt)}</time></div></li>)}</ol></div> : <div className="py-14 text-center"><Gavel className="mx-auto h-8 w-8 text-[#7a9fa3]" /><p className="mt-4 text-sm font-semibold text-[#506b83]">{cases.length ? "Select a case to reveal its timeline." : "No case records yet."}</p><p className="mt-2 text-sm text-[#718196]">A case lifecycle appears here once a record has been created.</p></div>}</CardContent></Card></div>;
}
