export interface OfficialAuthoritySeed {
  stateUt: string;
  authorityType: "CYBER_CELL" | "GRIEVANCE_OFFICER";
  authorityName: string;
  officerName: string;
  designation: string;
  officialEmail: string;
  phone?: string;
  sourceName: string;
  sourceUrl: string;
  lastVerifiedAt: Date;
}

export const OFFICIAL_CYBER_AUTHORITIES: OfficialAuthoritySeed[] = [
  // 1. Andaman & Nicobar
  {
    stateUt: "Andaman and Nicobar Islands",
    authorityType: "CYBER_CELL",
    authorityName: "Andaman & Nicobar Cyber Crime Police Station",
    officerName: "Sh. Jitendra Kumar Meena, IPS",
    designation: "SSP (CID)",
    officialEmail: "spcid.and@nic.in",
    phone: "03192-232334",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 2. Andhra Pradesh
  {
    stateUt: "Andhra Pradesh",
    authorityType: "CYBER_CELL",
    authorityName: "Andhra Pradesh Cyber Crime Investigation Cell (CID)",
    officerName: "Sh. Adhiraj Singh Rana",
    designation: "IPS, S.P Cyber Crimes, CID",
    officialEmail: "cybercrimes1930@cid.appolice.gov.in",
    phone: "0863-2340559",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 3. Arunachal Pradesh
  {
    stateUt: "Arunachal Pradesh",
    authorityType: "CYBER_CELL",
    authorityName: "Arunachal Pradesh Cyber Crime Cell (SIT)",
    officerName: "Sh Shivendu Bhushan",
    designation: "IPS",
    officialEmail: "spsit@arunpol.nic.in",
    phone: "9436040703",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 4. Assam
  {
    stateUt: "Assam",
    authorityType: "CYBER_CELL",
    authorityName: "Assam Cyber Crime Investigation Cell (CID)",
    officerName: "Sh. Saurav Jyoti Saikia",
    designation: "APS, SP Cyber Crime-2, CID",
    officialEmail: "sp-cid-cyber2@assampolice.gov.in",
    phone: "0361-2521618",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 5. Bihar
  {
    stateUt: "Bihar",
    authorityType: "CYBER_CELL",
    authorityName: "Bihar Cyber Crime Investigation Unit",
    officerName: "Shri. Sushil Kumar IPS",
    designation: "SP",
    officialEmail: "cybercell-bih@nic.in",
    phone: "0612-2238098",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 6. Chandigarh
  {
    stateUt: "Chandigarh",
    authorityType: "CYBER_CELL",
    authorityName: "Chandigarh Cyber Crime Investigation Cell",
    officerName: "Ms. Geetanjali",
    designation: "SP, Cyber Crime",
    officialEmail: "spops-chd@nic.in",
    phone: "0172-2700056",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 7. Chhattisgarh
  {
    stateUt: "Chhattisgarh",
    authorityType: "CYBER_CELL",
    authorityName: "Chhattisgarh State Cyber Crime Police Station (PHQ)",
    officerName: "Sh. Kavi Gupta",
    designation: "AIG",
    officialEmail: "aigtech-phq.cg@gov.in",
    phone: "0771-2511989",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 8. Dadra & Nagar Haveli and Daman & Diu
  {
    stateUt: "Dadra and Nagar Haveli and Daman and Diu",
    authorityType: "CYBER_CELL",
    authorityName: "DNH & DD Cyber Crime Cell",
    officerName: "Sh. Ketan Bansal",
    designation: "IPS",
    officialEmail: "sp-dmn-dd@nic.in",
    phone: "0260-2220140",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 9. Delhi
  {
    stateUt: "Delhi",
    authorityType: "CYBER_CELL",
    authorityName: "Delhi Police Special Cell / IFSO Cyber Unit",
    officerName: "Sh. Vinit Kumar, IPS",
    designation: "DCP/IFSO",
    officialEmail: "dcp-ifso@delhipolice.gov.in",
    phone: "011-20892633",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 10. Goa
  {
    stateUt: "Goa",
    authorityType: "CYBER_CELL",
    authorityName: "Goa Cyber Crime Police Station (Ribandar)",
    officerName: "Shri Rajendra Raut Dessai",
    designation: "SP, Cyber Crime",
    officialEmail: "spcyber@goapolice.gov.in",
    phone: "0832-2420883",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 11. Gujarat
  {
    stateUt: "Gujarat",
    authorityType: "CYBER_CELL",
    authorityName: "Gujarat State Cyber Crime Cell (CID Crime)",
    officerName: "Shri. Vivek Bheda",
    designation: "Superintendent of Police",
    officialEmail: "cc-cid@gujarat.gov.in",
    phone: "079-23250798",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 12. Haryana
  {
    stateUt: "Haryana",
    authorityType: "CYBER_CELL",
    authorityName: "Haryana State Cyber Crime Police Station (PHQ Panchkula)",
    officerName: "Sh. Sibash Kabiraj",
    designation: "IPS, ADGP Cyber Haryana",
    officialEmail: "sp-cybercrimephq.pol@hry.gov.in",
    phone: "0172-2524058",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 13. Himachal Pradesh
  {
    stateUt: "Himachal Pradesh",
    authorityType: "CYBER_CELL",
    authorityName: "Himachal Pradesh Cyber Crime Police Station (CID)",
    officerName: "IPS Mohit Chawla",
    designation: "DIG",
    officialEmail: "dig-cybercr-hp@nic.in",
    phone: "0177-2620331",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 14. Jammu & Kashmir
  {
    stateUt: "Jammu and Kashmir",
    authorityType: "CYBER_CELL",
    authorityName: "J&K Cyber Investigation & Cyber Crime Centre (CICE)",
    officerName: "Sh. Ramnesh Gupta",
    designation: "JEPS, SSP CICE J&K",
    officialEmail: "ssp-cicejk@jkpolice.gov.in",
    phone: "0191-25822926",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 15. Jharkhand
  {
    stateUt: "Jharkhand",
    authorityType: "CYBER_CELL",
    authorityName: "Jharkhand Cyber Crime Police Station (CID Ranchi)",
    officerName: "Sh. Ehtesham Waquarib",
    designation: "IPS, SP, CID",
    officialEmail: "sp-cid@jhpolice.gov.in",
    phone: "0651-2220060",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 16. Karnataka
  {
    stateUt: "Karnataka",
    authorityType: "CYBER_CELL",
    authorityName: "Karnataka State Cyber Crime Division (CID Bengaluru)",
    officerName: "Sh. S Ravi",
    designation: "ADGP/Intl.",
    officialEmail: "spctrcid@ksp.gov.in",
    phone: "080-22942475",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 17. Kerala
  {
    stateUt: "Kerala",
    authorityType: "CYBER_CELL",
    authorityName: "Kerala Cyber Operations Police Headquarters",
    officerName: "Sh. Ankit Ashokan",
    designation: "IPS, SP Cyber Crime",
    officialEmail: "spcyberops.pol@kerala.gov.in",
    phone: "0471-2300042",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 18. Ladakh
  {
    stateUt: "Ladakh",
    authorityType: "CYBER_CELL",
    authorityName: "Ladakh Cyber Crime Cell (PHQ UT Ladakh)",
    officerName: "Sh. Altaf Ahmad Shah",
    designation: "IPS, SSP",
    officialEmail: "soto-igp@police.ladakh.gov.in",
    phone: "9541902324",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 19. Lakshadweep
  {
    stateUt: "Lakshadweep",
    authorityType: "CYBER_CELL",
    authorityName: "Lakshadweep Cyber Crime Unit (Kavaratti)",
    officerName: "Sh. Utkarsha",
    designation: "IPS, SP Cyber Crime",
    officialEmail: "lak-sop@nic.in",
    phone: "04896262258",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 20. Madhya Pradesh
  {
    stateUt: "Madhya Pradesh",
    authorityType: "CYBER_CELL",
    authorityName: "Madhya Pradesh State Cyber Police Headquarters (Bhopal)",
    officerName: "Sh. Shiyas A",
    designation: "IG Cyber",
    officialEmail: "dig2-cybercell@mppolice.gov.in",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 21. Maharashtra
  {
    stateUt: "Maharashtra",
    authorityType: "CYBER_CELL",
    authorityName: "Maharashtra Cyber Headquarters (Mumbai)",
    officerName: "Sh. Sanjay Shintre",
    designation: "DIG Cyber Crime Maharashtra",
    officialEmail: "dig.cbr-mah@gov.in",
    phone: "022-22160080",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 22. Manipur
  {
    stateUt: "Manipur",
    authorityType: "CYBER_CELL",
    authorityName: "Manipur State Cyber Crime Police Station",
    officerName: "Shri N. John",
    designation: "Superintendent of Police",
    officialEmail: "sp-cybercrime.mn@manipur.gov.in",
    phone: "0385-2444888",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 23. Meghalaya
  {
    stateUt: "Meghalaya",
    authorityType: "CYBER_CELL",
    authorityName: "Meghalaya Cyber Crime Wing (CID Shillong)",
    officerName: "Shri Basant Kumar Mishra, MPS",
    designation: "DSP",
    officialEmail: "ccw-meg@gov.in",
    phone: "9402519391",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 24. Mizoram
  {
    stateUt: "Mizoram",
    authorityType: "CYBER_CELL",
    authorityName: "Mizoram State Cyber Crime Police Station (Aizawl)",
    officerName: "Sh. Zonun Sanga",
    designation: "MPS",
    officialEmail: "cybercrime.sp@mizoram.gov.in",
    phone: "0389-2334682",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 25. Nagaland
  {
    stateUt: "Nagaland",
    authorityType: "CYBER_CELL",
    authorityName: "Nagaland Cyber Crime Police Station (CID Kohima)",
    officerName: "Sh. Vikram M Khalate",
    designation: "IPS, IGP CID",
    officialEmail: "spcyber-ngl@gov.in",
    phone: "6009308003",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 26. Odisha
  {
    stateUt: "Odisha",
    authorityType: "CYBER_CELL",
    authorityName: "Odisha State Cyber Crime Police Station (CID-CB Cuttack)",
    officerName: "Shri. Shefeen Ahamed K, IPS",
    designation: "IGP, CID CB",
    officialEmail: "igp2-cidcb@odishapolice.gov.in",
    phone: "0674-2913100",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 27. Puducherry
  {
    stateUt: "Puducherry",
    authorityType: "CYBER_CELL",
    authorityName: "Puducherry Cyber Crime Police Station",
    officerName: "Ms. Shruti Yaragatti",
    designation: "IPS SP Cyber Crime",
    officialEmail: "cybercell-police.py@gov.in",
    phone: "0413-2231313",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 28. Punjab
  {
    stateUt: "Punjab",
    authorityType: "CYBER_CELL",
    authorityName: "Punjab State Cyber Crime Division (SAS Nagar / Mohali)",
    officerName: "Jashandeep Singh Gill",
    designation: "Superintendent of Police",
    officialEmail: "aigcc@punjabpolice.gov.in",
    phone: "0172-2226258",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 29. Rajasthan
  {
    stateUt: "Rajasthan",
    authorityType: "CYBER_CELL",
    authorityName: "Rajasthan Cyber Crime Police Station (SCRB Jaipur)",
    officerName: "Shri Shantanu Kumar Singh",
    designation: "Superintendent of Police",
    officialEmail: "sp.cybercrime@rajpolice.gov.in",
    phone: "01412821741",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 30. Sikkim
  {
    stateUt: "Sikkim",
    authorityType: "CYBER_CELL",
    authorityName: "Sikkim Cyber Crime Police Station (CB-CID Gangtok)",
    officerName: "Sh. Tenzing Loden Lepcha",
    designation: "IPS, DIGP CB-CID",
    officialEmail: "spcid@sikkimpolice.nic.in",
    phone: "9046245066",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 31. Tamil Nadu
  {
    stateUt: "Tamil Nadu",
    authorityType: "CYBER_CELL",
    authorityName: "Tamil Nadu Cyber Crime Wing (CCD Chennai)",
    officerName: "Ms. Shahnaz Illiyas",
    designation: "Superintendent of Police Cyber",
    officialEmail: "sp1-ccdtnpolice@gov.in",
    phone: "044-29580300",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 32. Telangana
  {
    stateUt: "Telangana",
    authorityType: "CYBER_CELL",
    authorityName: "Telangana Cyber Security Bureau (TGCSB)",
    officerName: "Ms. B. Sai Sri",
    designation: "SP TGCSB",
    officialEmail: "spoperations-csb-ts@tspolice.gov.in",
    phone: "040-29320049",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 33. Tripura
  {
    stateUt: "Tripura",
    authorityType: "CYBER_CELL",
    authorityName: "Tripura Cyber Crime Police Station (Agartala)",
    officerName: "Sh. Nabadwip Jamatia",
    designation: "TPS",
    officialEmail: "spcybercrime@tripurapolice.nic.in",
    phone: "0381-2376979",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 34. Uttarakhand
  {
    stateUt: "Uttarakhand",
    authorityType: "CYBER_CELL",
    authorityName: "Uttarakhand Special Task Force / Cyber Crime Police Station",
    officerName: "Sh. Nilesh Anand Bharne",
    designation: "IG Cyber Crime/STF",
    officialEmail: "nileshanad.bharne@ips.gov.in",
    phone: "0135-2655900",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 35. Uttar Pradesh
  {
    stateUt: "Uttar Pradesh",
    authorityType: "CYBER_CELL",
    authorityName: "Uttar Pradesh Cyber Crime Headquarters (Lucknow)",
    officerName: "Sh. Rajesh Kumar",
    designation: "SP, Cyber Crime",
    officialEmail: "sp-cyber.lu@up.gov.in",
    phone: "0522-2390538",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
  // 36. West Bengal
  {
    stateUt: "West Bengal",
    authorityType: "CYBER_CELL",
    authorityName: "West Bengal Cyber Crime Wing (CID Bhabani Bhawan)",
    officerName: "Sh. Suresh Kumar Chadive",
    designation: "IPS, DIG Cyber Crime",
    officialEmail: "dig1-ccw@policewb.gov.in",
    phone: "033 22021200",
    sourceName: "National Cyber Crime Reporting Portal",
    sourceUrl: "https://cybercrime.gov.in/",
    lastVerifiedAt: new Date("2026-08-23"),
  },
];
